# Generated by Django 5.1.7 on 2025-03-13 05:49

from django.db import migrations


def add_initial_categories(apps, schema_editor):
    Category = apps.get_model('mmo_board', 'Category')
    categories = [
        "Танки", "Хилы", "ДД", "Торговцы", "Гилдмастеры",
        "Квестгиверы", "Кузнецы", "Кожевники", "Зельевары", "Мастера заклинаний"
    ]
    for category_name in categories:
        Category.objects.create(name=category_name)


class Migration(migrations.Migration):
    dependencies = [
        ('mmo_board', '0001_initial'),  # Зависимость от первой миграции
    ]

    operations = [
        migrations.RunPython(add_initial_categories),
    ]
